fixtures:
  repositories:
    docker:
      repo: 'https://github.com/puppetlabs/puppetlabs-docker.git'
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    puppet_conf:
      repo: 'https://github.com/puppetlabs/puppet_conf.git'
    facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    provision: 'https://github.com/puppetlabs/provision.git'
  symlinks:
    dropsonde: "#{source_dir}"